import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
    return (
        <div className="container">
            <Head>
                <title>Flatterer | Nice Tw*tt*r</title>
                <meta name="description" content="Generated by create next app and B" />
                <link rel="icon" href="" />
            </Head>
        </div>
    )
}

export default Home
